// ============================================================
// Candypad QMK Keymap — generated by Candypad Configurator
// Flash with:  qmk compile -kb binepad/candypad -km my_keymap
// Docs: https://docs.qmk.fm
// ============================================================

#include QMK_KEYBOARD_H

// ── Layer indices ─────────────────────────────────────────
enum layers {
    _BASE = 0,
    _FN,
    _LAYER2,
    _LAYER3,
};

// ── Keymaps ───────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        KC_MUTE, KC_BTN3,
        KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7, KC_P8, KC_P9, KC_PPLS,
        KC_P4, KC_P5, KC_P6,
        KC_P1, KC_P2, KC_P3, KC_PENT,
        KC_P0,           KC_PDOT
    ),

    [_FN] = LAYOUT(
        KC_TRNS, KC_TRNS,
        MO(1), KC_F1, KC_F2, RGB_TOG,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER2] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER3] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    )
};


#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(MS_WHLU, MS_WHLD) },
    [_FN] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
};
#endif



static int8_t oled_vol = 5; // 0-10, tracked via encoder




oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_0;
}

bool oled_task_user(void) {
    // Let the board's candypad_oled.c render the default dashboard
    return true; // true = let board render default dashboard, false = we handled it ourselves
}

bool candypad_render_default_user(void) {



    // Volume bar
    oled_set_cursor(0, 3);
    oled_write_P(PSTR("VOL "), false);
    for (uint8_t i = 0; i < 10; i++) {
        oled_write_char(i < oled_vol ? 0xFF : '-', false);
    }


    return false; // false = let board continue with its default rendering
}


